---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
    
---

```{r, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, message = FALSE)
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

\ \par

## Extract data in 2016 

```{r}
data(rest_inspec)

inspec_2016 =     
  rest_inspec %>%
  janitor::clean_names() %>%
  filter(
    substr(inspection_date, 1, 4) == 2016,   # only data that is inspected in 2016
    boro != 'Missing') %>%                   # remove the missing and na
  drop_na(score)

```

\ \par

## Scatterplot 

```{r}
scatter_plot = 
  inspec_2016 %>%
  group_by(boro,inspection_date) %>%
  mutate(mean_score = mean(score)) %>%
  select(boro, inspection_date, mean_score) %>%
  plot_ly(x = ~inspection_date, y = ~mean_score, color = ~boro, type = 'scatter', mode = "markers",colors = 'viridis') %>%
  layout(
    xaxis = list(title = "Inspection Date"),
    yaxis = list(title = "Mean Score")
  )

```

\ \par

## Boxplot
```{r}
box_plot = 
  inspec_2016 %>%
  plot_ly(y = ~score, color = ~boro, type = 'box', colors = 'viridis') %>%
  layout(
    xaxis = list(title = "Borough"),  # boxplot of scores by borough
    yaxis = list(title = "Score")
    )

```

\ \par

## Barplot
```{r}
Score_cuisine = 
  inspec_2016 %>%
  group_by(cuisine_description) %>%
  summarize(mean_score = mean(score)) %>%
  arrange(-mean_score, cuisine_description) %>%  # get the top 10
  head(10)

bar_plot = 
  Score_cuisine %>%
  mutate(cuisine_description = fct_reorder(cuisine_description, -mean_score)) %>%
  plot_ly(x = ~reorder(cuisine_description, -mean_score), y = ~mean_score, color = ~cuisine_description, type = 'bar', colors = 'viridis') %>%
  layout(
    xaxis = list(title = "Cuisine Type"),
    yaxis = list(title = "Mean Score")
    ) 


```

\ \par
## Plots Display

\ \par    
### Scatterplot of NYC Restaurants' Mean Score over Time in 2016
    
```{r}
scatter_plot

```
   

\ \par
### Boxplot of Score in 5 NYC Boroughs in 2016

```{r}
box_plot

```   
 
\ \par
### Barplot of Top 10 Most Hazardous Cuisine Types in NYC in 2016
    
```{r}
bar_plot

```
